### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by flashwave** [flashwave/sakurako#1]
When I'm nearing the completion of something I tend to forget the smaller details I still need to work on.

- [x] Add a `case 'flwarn:'` to `case 'flood':`.
- [x] Load sound and language json files on demand as opposed to all at once on load to tone down load time.
- [x] Add a sequenced initialiser so I can get rid of the synchronous AJAX requests.
- [x] Add language support.
- [x] Fix server side sanitisation collisions in SockLegacy.
- [x] Add toggleable tab close confirmation.
- [x] Automatically attempt to reconnect after losing connection.
- [x] Add emoticons.
- [x] Add URL detecting thing for auto-linking as well as auto-embedding.
- [x] Switch font to Noto Sans.
- [x] Reimplement window blinking.
- [x] Add user notifications.
- [x] ~~Add support for image camo/on demand https proxying.~~ Handled in the resolver.
